In [ ]:
!pip install tf-keras

  Using cached tf_keras-2.21.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl.metadata (4.4 kB)
  Using cached protobuf-7.35.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
  Using cached h5py-3.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Using cached tf_keras-2.21.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 MB 789.9 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 133.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 327.1/327.1 kB 25.4 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
  Attempting uninstall: h5py
    Found existing installation: h5py 3.16.0
    Uninstalling h5py-3.16.0:
      Successfully uninstalled h5py-3.16.0
  Attempting uninstall: tensorflow
    Found exi

In [ ]:
#!pip install transformers==4.52.4 tensorflow==2.19.0 torch

In [ ]:
import os
os.environ["TF_KERAS"] = "1"

In [ ]:

from transformers import AutoTokenizer, TFAutoModelForQuestionAnswering
import tensorflow as tf

# Load tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-cased-distilled-squad"
)

model = TFAutoModelForQuestionAnswering.from_pretrained(
    "distilbert-base-cased-distilled-squad"
)

question = "Where do you work?"
context = "My name is Ruchika and I work at GA Services in Bangalore."

# Tokenize
inputs = tokenizer(
    question,
    context,
    return_tensors="tf"
)

print(inputs)

# Forward pass
outputs = model(inputs)
print(outputs)

# Start and end logits
start_logits = outputs.start_logits
end_logits = outputs.end_logits

# Predicted answer span
answer_start = tf.argmax(start_logits, axis=1).numpy()[0]
answer_end = tf.argmax(end_logits, axis=1).numpy()[0] + 1

# Decode answer
answer = tokenizer.decode(
    inputs["input_ids"][0][answer_start:answer_end]
)

print("Question:", question)
print("Context:", context)
print("Answer:", answer)

/usr/local/lib/python3.12/dist-packages/torch_xla/__init__.py:246: UserWarning: `tensorflow` can conflict with `torch-xla`. Prefer `tensorflow-cpu` when using PyTorch/XLA. To silence this warning, `pip uninstall -y tensorflow && pip install tensorflow-cpu`. If you are in a notebook environment such as Colab or Kaggle, restart your notebook runtime afterwards.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/jax/_src/cloud_tpu_init.py:86: UserWarning: Transparent hugepages are not enabled. TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer. If not already set, you may need to enable transparent hugepages in your VM image (sudo sh -c "echo always > /sys/kernel/mm/transparent_hugepage/enabled")
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (http

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFDistilBertForQuestionAnswering.

All the weights of TFDistilBertForQuestionAnswering were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForQuestionAnswering for predictions without further training.


{'input_ids': <tf.Tensor: shape=(1, 23), dtype=int32, numpy=
array([[  101,  2777,  1202,  1128,  1250,   136,   102,  1422,  1271,
         1110,   155, 16643,  1968,  1105,   146,  1250,  1120, 20173,
         4326,  1107, 14560,   119,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 23), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1]], dtype=int32)>}
TFQuestionAnsweringModelOutput(loss=None, start_logits=<tf.Tensor: shape=(1, 23), dtype=float32, numpy=
array([[-2.544649  , -4.020597  , -6.4753714 , -5.7535973 , -5.9559493 ,
        -3.4424734 , -0.35844815,  0.14481874, -3.523421  , -5.783063  ,
         0.41057622, -5.7585993 , -4.3303857 , -1.7089453 ,  2.360352  ,
         1.0435683 ,  3.8564944 , 10.278097  , -0.05172309,  1.7535732 ,
         8.147418  , -1.6818745 , -0.3584218 ]], dtype=float32)>, end_logits=<tf.Tensor: shape=(1, 23), dtype=float32, numpy=
array([[-0.6323984 , -3.4798303 , -6.2888722 , -

In [ ]:
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM, pipeline

# Load tokenizer and model explicitly with from_pt=True
tokenizer = AutoTokenizer.from_pretrained("sshleifer/distilbart-cnn-12-6")
model = TFAutoModelForSeq2SeqLM.from_pretrained("sshleifer/distilbart-cnn-12-6", from_pt=True)

summarizer = pipeline(
    "summarization",
    model=model, # Pass the loaded TF model
    tokenizer=tokenizer # Pass the loaded tokenizer
)

text = """
*Dilwale Dulhania Le Jayenge (DDLJ)* is a landmark Bollywood romantic film released in 1995.
     Directed by Aditya Chopra and starring Shah Rukh Khan and Kajol, the movie tells the story of Raj and Simran,
      two young Indians who meet and fall in love during a trip across Europe. Their journey is filled with romance, humor,
       and emotional moments that have captivated audiences for decades.

The film beautifully blends love, family values, and tradition, emphasizing the importance of respecting one's parents
while pursuing personal happiness. Known for its unforgettable music, memorable dialogues, and strong performances,
 DDLJ became one of the biggest successes in Indian cinema and continues to be regarded as one of the greatest Bollywood films
  ever made.


"""

summary = summarizer(
    text,
    max_length=150,
    min_length=30,
    do_sample=False
)

print(summary[0]["summary_text"])

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBartForConditionalGeneration: ['model.decoder.embed_tokens.weight', 'model.encoder.embed_tokens.weight']
- This IS expected if you are initializing TFBartForConditionalGeneration from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBartForConditionalGeneration from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBartForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBartForConditionalGeneration for predictions without further training.
Device set to use 0


 The film tells the story of Raj and Simran, two young Indians who meet and fall in love during a trip across Europe . Known for its unforgettable music, memorable dialogues, and strong performances, DDLJ became one of the biggest successes in Indian cinema .
